# Generated by Django 4.2.6 on 2023-10-31 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="replies",
                to="app.comments",
            ),
        ),
    ]
