# Generated by Django 4.2.6 on 2023-11-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_post_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(blank=True, null=True, upload_to="videos/")),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
